SeasideSt/Seaside

.travis.yml

Do not run Pharo 4 with default config, it is included explicitly with a custom configuration.

Do not run Pharo 4 with default config

---

repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinesecurity..st

Remove duplication in baseline security.
Fixes #1102

1102-Remove-duplication-between-squeak-and-pharo-in-baseline-security

---

repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/startWelcomeSeasideAdaptorInPharo.st
repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/startWelcomeSeasideAdaptorInSqueak.st

Do not reference classes that are not loaded directly in the baseline to avoid undefined.
Because then you cannot change the method if you only load the baseline to work on it and you'll get undeclared in the logs.

avoid_undeclared_in_logs

---

repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinegemstone..st

[All of the GemStone tests passed](https://travis-ci.org/SeasideSt/Seaside/builds/490810666) and the only changes I've made is to the `baselineGemstone` method .. all of the Pharo builds failed `WANoDuplicateUuidsTest` so this must be a pharo thing ... I will go ahead a merge when travis is done, since I am hoping to use this for internal test runs before 3.5.0 is released ...

Issue #88: add 3.5.0 to baseline ... local tests are passing

---

.smalltalk.ston
repository/Seaside-Adaptors-FastCGI.package/WAFastCGIAdaptor.class/instance/addCookieRFC2965.toStream..st
repository/Seaside-Adaptors-FastCGI.package/WAFastCGIAdaptor.class/instance/addCookieRFC6265.toStream..st
repository/Seaside-Core.package/WACookie.class/README.md

fix #1115.
Take a look at [this comment](https://github.com/SeasideSt/Seaside/issues/1115#issuecomment-473408429) where I explain the rationale for the changes.

fix for Issue #1115

---

.travis.yml

My previous commit was not good. We already test on Squeak 5.2,
the tests are green and it is even in the badges.

Revert allowing Squeak 5.2 failures

---

repository/Seaside-Core.package/WARemoteAddressProtectionFilter.class/instance/remoteAddressFromRequest..st
repository/Seaside-Core.package/WARequest.class/instance/forwarded.st
repository/Seaside-Core.package/WARequest.class/instance/forwardedFor.st
repository/Seaside-Session.package/WAIPSessionTrackingStrategy.class/instance/remoteAddressFromRequest..st
repository/Seaside-Session.package/WAIPSessionTrackingStrategy.class/instance/sessionIdFromContext..st
repository/Seaside-Tests-Core.package/WARequestTest.class/instance/testForwarded.st
repository/Seaside-Tests-Core.package/WARequestTest.class/instance/testForwardedFor.st

Remove code duplication and fix for retrieving value in forwarded header -or- the remoteAddress when relying on the origin ip in the `WARemoteAddressProtectionFilter` and `WAIPSessionTrackingStrategy`
In addition, the`WARemoteAddressProtectionFilter` was storing the value from the forwarded header (if present) but the first comparison was still returning the remoteAddress anyway. So this can never have worked in the case where using the header was necessary.
Fixes for 1152

Remove code duplication and fix remoteaddress-based tracking strategy and filter

---

repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/README.md
repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/class/onBlock..st
repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/instance/contents..st
repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/instance/contents.st
repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/instance/initializeOnBlock..st
repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/instance/seasideMimeDocumentType..st
repository/Seaside-Tests-Core.package/WABlockMimeDocument.class/properties.json
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/instance/testAsMIMEDocumentByteArray.st
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/instance/testAsMIMEDocumentByteArrayColon.st
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/instance/testAsMIMEDocumentString.st
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/instance/testAsMIMEDocumentStringColon.st
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/instance/testByteArraySeasideMimeDocumentType.st
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/instance/testStringSeasideMimeDocumentType.st
repository/Seaside-Tests-Core.package/WABlockMimeDocumentTest.class/properties.json

Add dynamic mime document in tests as an example on how to dynamically generate resources.
Closes #1188

Add dynamic mime document in tests

---

repository/Zinc-Seaside.package/ZnZincServerAdaptor.class/instance/responseFrom..st

Fixes  to multiple value headers convertion #1211

---

repository/Seaside-Tests-Core.package/WARequestTest.class/instance/testPostFields.st

Hi,
I submit this pull request to suggest some improvements in the test method #testPostFields to cover some corner cases in the class WARequest.
By including the lines #5-#10 the test will now execute methods in the class under test which previously were not covered by WARequestTest (isXmlHttpRequest, headers, remoteAddress, isPost, sslSessionId). This will also guard against a WARRequest object which is improperly initialized.
Line #6 verifies that the WARRequest does not have an XMLHttpRequest header by default.
Line #9 on the other hand verifies that WARequest is properly initialized via #method:uri: and ‘POST’ argument.
By including Line #15, the test will guard against sending #bodyDecoded when charSet isNil (a WAMimeType(application/x-www-form-urlencoded) has a nil charSet).
Note …

Improving WARequestTest >> testPostFields

---

.travis.yml
repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/projectClass.st

fix #1226 and move Squeak-5.2 to allowed failures (#1229).
While the 3.6.0 port did not require any direct changes to the Seaside code itself, a number of other projects were changed in order to get all of the Seaside tests to pass for 3.5.4 and 3.6.0.
@jbrichau, no review required as the changes do not involve the Seaside code base ... other than adding #projectClass to the baseline, to complete the contract for metadataless operation ... 
There was a bug in Metacello/metacello#531 that reared it's head when I added the #projectClass method and that may have been the reason it was not done when the other changes were made, but that bug is fixed.

GemStone 3.6 port complete

---

repository/Seaside-Tests-Functional.package/WALotsaLinksFunctionalTest.class/instance/renderContentOn..st

The use of `Integer>>#to:do:` to generate the callbacks causes variable references issues in VAST, so to avoid having to patch the method in VAST, we modify it directly upstream with a change that is innocuous to other dialects.

Changes iteration to use Interval

---

repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/expectedFailures.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testButtonFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testCanvasTagFunctionalTest.st

This fixes some disabled Parasol tests that were broken because of a change in chromedriver (see https://bugs.chromium.org/p/chromium/issues/detail?id=1205107)

Adapt tests to changes in chromedriver and Parasol

---

repository/Seaside-Canvas.package/WAHtmlCanvas.class/class/configureRenderContext..st
repository/Seaside-Core.package/WABuilder.class/instance/render.on..st
repository/Seaside-Core.package/WARenderer.class/class/configureRenderContext..st
repository/Seaside-Tests-Canvas.package/WABuilderCanvasTest.class/instance/testBodyWithDecorations.st
repository/Seaside-Tests-Canvas.package/WACanvasTestComponent.class/instance/renderContentOn..st
repository/Seaside-Tests-Canvas.package/WACanvasTestComponent.class/properties.json
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/class/rendererClass.st
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/class/tagName..st
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/instance/initialize.st
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/instance/renderContentOn..st
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/instance/tagName..st
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/instance/tagName.st
repository/Seaside-Tests-Canvas.package/WACanvasTestDecoration.class/properties.json
repository/Seaside-Tests-Functional.package/WALotsaLinksFunctionalTest.class/instance/renderContentOn..st

Rendering components directly from from a `WABuilder` skipped visiting the decorations (if any) of the rendered components.
So in the following code:
```smalltalk
| component |
component := (SomeComponent new) 
addDecoration: (SomeDecoration new);
yourself.
WAHtmlCanvas builder
fullDocument: true;
rootBlock: [ :root | component updateRoot: root ];
render: [ :html | html render: component ]
```
The instance of `SomeComponent` will be rendered without its decorations.
The issue comes from the `WARenderContext` being initialized generically in `WABuilder` but with a specific visitor (`WARenderingGuide`) in `WARenderPhaseContinuation`.
I propose a change that is idempotent to other kind of canvases (XML, JSON, etc.) , but gives a method in `WAHtmlCanvas` to hook in the initialization of the …

Fixes WARenderContext using the wrong visitor for WAHtmlCanvas

---

.github/workflows/ci.yml

The CI step to load Chrome needs to set the Google repo as the source so we always load the actual latest stable.
This fixes the CI.

CI: fix load of latest Chrome

---

.smalltalk.ston
repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinecommon..st

We broke the dependency of Parasol on Seaside in https://github.com/SeasideSt/Parasol/pull/52 to make loading of Parasol in Metacello projects easier to deal with.
A year back (e.g. https://github.com/SeasideSt/Seaside/commit/a30e9be0f959ff9fc813eebb831aca9241759174), we broke the dependency from Seaside to Parasol, but this proves to be complicating builds that load Seaside and want to run the Seaside Functional tests with Parasol.
By removing the dependency of Parasol on Seaside _and_ pulling in Parasol automatically when loading the Seaside tests, we hope to reverse the problem of the dependency cycle in a more convenient way for those projects.

Baseline parasol cycle reversal

---

repository/Seaside-Tests-Flow.package/WAFlowErrorFunctionalTest.class/instance/renderErrorWithCallOn..st
repository/Seaside-Tests-Functional.package/WAExceptionFunctionalTest.class/instance/renderHandlerConfigurationOn..st
repository/Seaside-Tests-Functional.package/WAExceptionFunctionalTest.class/instance/renderPostErrorOn..st
repository/Seaside-Tests-Functional.package/WAExceptionFunctionalTest.class/instance/renderRenderErrorOn..st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/expectedFailures.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/scrollWindowBy..st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testDateSelectorFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testExceptionFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowErrorFunctionalTest.st

Some fixes and additions to the parasol tests executing the functional tests:
- The functional date test was erroring since January 1st 2022 because the selector does not display the year 2020 anymore
- Added tests for exception handler testing

More tests and fixes

---

repository/Seaside-Tests-Core.package/WAMutexTest.class/instance/testSelfTerminate.st

Use process priority rather than semaphore to ensure the spawned process is terminated in the test case.
See #1291 for more info.
Thanks @martinmcclure for the test fix!

Fix WAMutexTest>>testSelfTerminate

---

repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinecommon..st
repository/Seaside-Core.package/WABufferedResponse.class/instance/writeContentAsStringOn..st
repository/Seaside-Core.package/WAComboResponse.class/instance/writeContentAsStringOn..st
repository/Seaside-Core.package/WAResponse.class/instance/writeContentAsStringOn..st
repository/Seaside-Core.package/WAResponse.class/instance/writeOn..st
repository/Seaside-Core.package/WAServerAdaptor.class/instance/responseFor..st
repository/Seaside-Core.package/WAStreamedResponse.class/instance/writeContentAsStringOn..st
repository/Seaside-Core.package/WAUrlEncoder.class/instance/nextPut..st
repository/Seaside-Tests-Core.package/WAResponseTest.class/instance/assertLines..st
repository/Seaside-Tests-Pharo-Core.package/WAGenericCodecTest.class/instance/asByteArray..st
repository/Seaside-Tests-Pharo-Core.package/WAGenericCodecTest.class/instance/testGenericCodecMacRoman.st
repository/Seaside-Tests-Pharo-Core.package/WAGenericCodecTest.class/instance/testGenericCodecUtf16be.st
repository/Seaside-Tests-Pharo-Core.package/WAGenericCodecTest.class/instance/testGenericCodecUtf16le.st
repository/Seaside-Tests-Pharo-Core.package/WAGenericCodecTest.class/instance/utf8ByteArray.st
repository/Seaside-Tests-Pharo-Core.package/WAPharoEncoderTest.class/instance/assert.next.startingAt.encoder.gives..st
repository/Seaside-Tests-Session.package/WASessionTest.class/instance/testRegisterDocumentHandler.st
repository/Seaside-Tests-UTF8.package/WABufferedResponseTest.extension/instance/testResetKeepsStreamKind.st
repository/Zinc-Seaside.package/ZnZincStreamingServerAdaptor.class/instance/responseFor..st

- Use the GRCodec>>encodedStringClass when initializing WAResponse subinstances
- Some utility methods for writing responses on a String-based stream for testing
- WAURLEncoder requires to encode UTF8 to a String always

Pharo9+ UTF8 encoding support using ZnUTF8Encoder

---

repository/Seaside-GemStone-Core.package/CharacterCollection.extension/instance/seasideMimeDocument.st

Fix #1246 
It add CharacterCollection>>seasideMimeDocument to Seaside-GemstoneCore but does not remove String>>seasideMimeDocument  which is in Seaside-Core.

fix https://github.com/SeasideSt/Seaside/issues/1246

---

repository/Javascript-Core.package/JSObject.class/instance/script.on..st
repository/Seaside-Core.package/WARequestContext.class/instance/newDocument.st
repository/Seaside-Core.package/WARequestContext.class/instance/newDocumentOn..st

When you render something by means of instantiating your own WABuilder, there was an unnecessary reference to the handler to obtain the scriptGenerator class.
This change delegates such decision to `WARequestContext>>#newDocument` which already considers the case of a nil handler.
I ran all the tests and it passes without issues, since it's mostly a refactoring.

Delegates JSObject>>#script:on: document creation to the requestContext.

---

repository/Seaside-Pharo-Development.package/Behavior.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/Behavior.extension/properties.json
repository/Seaside-Pharo-Development.package/Boolean.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/Boolean.extension/properties.json
repository/Seaside-Pharo-Development.package/CompiledBlock.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/CompiledBlock.extension/properties.json
repository/Seaside-Pharo-Development.package/CompiledMethod.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/CompiledMethod.extension/properties.json
repository/Seaside-Pharo-Development.package/InstructionStream.extension/instance/traversableInstVarIndexes.st
repository/Seaside-Pharo-Development.package/InstructionStream.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/Object.extension/instance/traversableIndexableVarIndexes.st
repository/Seaside-Pharo-Development.package/Object.extension/instance/traversableInstVarIndexes.st
repository/Seaside-Pharo-Development.package/Object.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/Process.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/Process.extension/properties.json
repository/Seaside-Pharo-Development.package/Symbol.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/Symbol.extension/properties.json
repository/Seaside-Pharo-Development.package/UndefinedObject.extension/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/UndefinedObject.extension/properties.json
repository/Seaside-Pharo-Development.package/WAMemory.class/class/initialize.st
repository/Seaside-Pharo-Development.package/WAMemory.class/instance/buildTable.st
repository/Seaside-Pharo-Development.package/WAMemory.class/instance/traverse.value.seen..st
repository/Seaside-Pharo-Development.package/WAMemory.class/instance/traverseWithMemory.seen..st
repository/Seaside-Pharo-Development.package/WAMemory.class/properties.json
repository/Seaside-Pharo-Development.package/WAMemoryItem.class/instance/traverseWithMemory.seen..st

- don't index into CompiledBlocks
- ignore immediate objects
- sort by total size by default
- replace ifs with method dispatches
Fixes #1336

Fix WAMemory on Pharo

---

repository/Seaside-JSON-Core.package/WAJsonParser.class/README.md
repository/Seaside-JSON-Core.package/WAJsonParser.class/instance/createCodePointFromSurrogatesHigh.low..st
repository/Seaside-JSON-Core.package/WAJsonParser.class/instance/isHighSurrogate..st
repository/Seaside-JSON-Core.package/WAJsonParser.class/instance/isLowSurrogate..st
repository/Seaside-JSON-Core.package/WAJsonParser.class/instance/parseCharacterHex.st
repository/Seaside-JSON-Core.package/WAJsonParser.class/instance/parseCharacterHexRaw.st
repository/Seaside-JSON-Core.package/WAJsonParser.class/properties.json
repository/Seaside-Tests-JSON.package/WAJsonParserTest.class/instance/supportsEmoji.st
repository/Seaside-Tests-JSON.package/WAJsonParserTest.class/instance/testNonBmpCodePoints.st
repository/Seaside-Tests-JSON.package/WAJsonParserTest.class/instance/testSurrogatePairs.st

Handle UTF-16 surrogate pairs in WAJsonParser

---

repository/Seaside-Core.package/WAServerManager.class/class/beDefault.st
repository/Seaside-Core.package/WAServerManager.class/class/default.st
repository/Seaside-Core.package/WAServerManager.class/class/initializeDefaultValueHolder.st
repository/Seaside-Core.package/WAServerManager.class/class/setDefault..st
repository/Seaside-Core.package/WAServerManager.class/properties.json
repository/Seaside-Tests-Core.package/WAServerManagerTest.class/instance/testBeDefault.st
repository/Seaside-Tests-Core.package/WAServerManagerTest.class/instance/testSetDefault.st
repository/Seaside-Tests-Core.package/WATestServerManager.class/README.md
repository/Seaside-Tests-Core.package/WATestServerManager.class/properties.json

VAST, and probably other dialects, have a subclass of WAServerManager that is used instead of it.
Since `WAServerManager[default]` is a class instance variable, then sending the message `default` to `WAServerManager` will always answer an instance of itself. Which is more troubling if you access it by means of `WAAdmin defaultServerManager`.
This PR modifies the `default` class instance variable to be a class variable (named `Default`), and provides a `beDefault` method that can be used on subclasses to be the "singleton" default.

Modifies WAServerManager to support subclasses to be defined as default

---

repository/Seaside-Core.package/GRPlatform.extension/instance/sourceFileEncoding.st
repository/Seaside-JSON-Core.package/JSJsonParser.class/class/isDeprecated.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/expectedFailures.st
repository/Seaside-Welcome.package/WAWelcomeFiles.class/instance/welcomeCss.st

Fixes #1326, #1360, #1359
Also disables the CORS functional webtest since it started failing in the github builds only...

Some fixes

---

repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/class/newForRBEnvironment..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/createAndSortTriplets..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/createHeaders.st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/createStringMethodRefDictionary..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/currentDateAndTime.st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/exportCatalog.st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/exportHeader.st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/exportHeaderLineKey.value..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/formatString..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/gatherTranslations.st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/rbEnvironment..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/stream..st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/instance/stream.st
repository/Seaside-Pharo-Gettext-Core.package/WAGetTextExporter.class/properties.json
repository/Seaside-Pharo-Gettext-Core.package/WATranslatedArgumentsFinder.class/instance/translatedArguments..st
repository/Seaside-Pharo-Gettext-Core.package/WATranslatedArgumentsFinder.class/instance/translatedArgumentsIn..st
repository/Seaside-Tests-Pharo-Gettext.package/WAGetTextExporterTest.class/instance/fileContentsOfPOTFile.st
repository/Seaside-Tests-Pharo-Gettext.package/WAGetTextExporterTest.class/instance/sortedTriplets.st
repository/Seaside-Tests-Pharo-Gettext.package/WAGetTextExporterTest.class/instance/sortedTripletsString.st
repository/Seaside-Tests-Pharo-Gettext.package/WAGetTextExporterTest.class/instance/testExportCatalog.st
repository/Seaside-Tests-Pharo-Gettext.package/WAGetTextExporterTest.class/instance/translationLiteralsArrayAsCompiledMethod.st

Tackles issues mentioned in https://github.com/SeasideSt/Seaside/issues/1369

Fix for issue #1369 (improvements for WAGettextExporter)

---

repository/Seaside-Canvas.package/WAAnchorTag.class/instance/charset..st
repository/Seaside-Canvas.package/WAAnchorTag.class/instance/name..st
repository/Seaside-Canvas.package/WAAnchorTag.class/instance/reverse..st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/acronym..st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/acronym.st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/big..st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/big.st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/embed..st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/embed.st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/menu..st
repository/Seaside-Canvas.package/WAHtmlCanvas.class/instance/menu.st
repository/Seaside-Canvas.package/WATableCellTag.class/instance/align..st
repository/Seaside-Canvas.package/WATableCellTag.class/instance/character..st
repository/Seaside-Canvas.package/WATableCellTag.class/instance/characterOffset..st
repository/Seaside-Canvas.package/WATableDataTag.class/instance/abbreviation..st
repository/Seaside-Canvas.package/WATableDataTag.class/instance/axis..st
repository/Seaside-Canvas.package/WATableDataTag.class/instance/scope..st
repository/Seaside-Core.package/WAContentElement.class/instance/charset..st
repository/Seaside-Core.package/WALinkElement.class/instance/reverse..st
repository/Seaside-Core.package/WAMetaElement.class/instance/charset..st
repository/Seaside-Core.package/WAMetaElement.class/instance/scheme..st

Mark the html tags and attributes that have been deprecated/removed in html5 as deprecated in Seaside

Deprecated html tags

---

repository/Seaside-Core.package/WAUrl.class/instance/initializeFromString..st
repository/Seaside-Tests-Core.package/WAUrlTest.class/instance/testNastyEdgeCasesParsing.st

This pull request fixes issue #1376 by making `#initializeFromString:` in WAUrl take into account that `://` can also be included in the query.
The example this pull request adds to `#testNastyEdgeCasesParsing` reflects the use of `#absolute:` in `#requestUrlFor:` in WAFastCGIRequestConverter: the argument to `#absolute:` is not a valid absolute URI as defined in [section 4.3 in RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-4.3), as it does not begin with a scheme, but it is a valid request target as defined in [section 3.2 in RFC 9112](https://www.rfc-editor.org/rfc/rfc9112.html#section-3.2). WAUrl and WAFastCGIRequestConverter should maybe be made to better distinguish between those.

Fix #initializeFromString: in WAUrl to take into account that ‘://’ can also be included in the query

---

repository/Zinc-Seaside.package/ZnZincServerAdaptor.class/instance/requestHeadersFor..st

This pull request fixes `#requestHeadersFor:` on ZnZincServerAdaptor to combine field values for repeated header field names.
[Section ‘5.2. Field Lines and Combined Field Value’ in RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.2) states:
> When a field name is only present once in a section, the combined "field value" for that field consists of the corresponding field line value. When a field name is repeated within a section, its combined field value consists of the list of corresponding field line values within that section, concatenated in order, with each field line value separated by a comma.
See also [section ‘6.3. Header Fields’](https://www.rfc-editor.org/rfc/rfc9110.html#section-6.3).
Example:
```smalltalk
request := String crlf join: #('GET / HTTP/1.1' …
```

Fix #requestHeadersFor: on ZnZincServerAdaptor to combine field values for repeated field names

---

repository/Seaside-Core.package/WAAbstractFileLibrary.class/instance/entityTagFor..st

Use #greaseAsByteArray when computing etag

---

.smalltalk.ston
repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinecommon..st
repository/BaselineOfSeaside3.package/monticello.meta/categories.st
repository/Seaside-Tests-Functional.package/WACORSFilterFunctionalTest.class/instance/baseUrl.st
repository/Seaside-Tests-Functional.package/monticello.meta/categories.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/expectedFailures.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testUploadFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testUploadFunctionalTestWithStreamingUploads.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/zincServer.st
repository/Seaside-Tests-Parasol.package/monticello.meta/categories.st
repository/Seaside-Zinc-Core.package/ZnStreamingMultiPartFormDataEntity.class/instance/parseMultiPartFileFieldWithMimePart.boundary.decodeWith..st
scripts/preLoading.st

Added a test for file uploads and fixed the (streaming) file uploads in GemStone.

File upload testing

---

repository/Seaside-Core.package/WANullScriptGenerator.class/instance/addLoadScript..st
repository/Seaside-Core.package/WANullScriptGenerator.class/instance/addLoadScriptFirst..st
repository/Seaside-Core.package/WAStyleElement.class/instance/tag.st

Fix protocol typo

---

repository/Seaside-Development.package/WADevelopmentFiles.class/instance/developmentCss.st

There are frameworks that place content at z-index 1000+ and light-boxes that place their content at z-index 10000.
To ensure that the WAToolbar always sits in front of other content, I always set it to a silly big number.
I thought this may be handy for others as well.

update z-index of wa-toolbar to 99999

---

repository/Seaside-Pharo110-Slime.package/WAChangesStateWhileRenderingRule.class/instance/afterCheck.mappings..st
repository/Seaside-Pharo110-Slime.package/WAUsesWrongRendererRule.class/instance/afterCheck.mappings..st
repository/Seaside-Tests-Slime.package/WASlimeTest.class/instance/testUsesWrongRenderer.st
repository/Seaside-Tests-Slime.package/monticello.meta/categories.st

Fixes false positives in Slime rules

Fix errors in Slime rules (due to code that was forgotten when moving from RB to Renraku framework)

---

repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/contents.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/messageCategoryList.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/messageList.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/packageNameOf..st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/packages.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/selectedClass.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/systemCategoryList.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/systemCategoryListIndex..st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/systemCategoryListIndex.st
repository/Seaside-Pharo-Development.package/monticello.meta/categories.st

This should help with all the deprecation warnings on Pharo 12 in logs.

Fix browser deprecations in Pharo 11

---

repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/packages.st
repository/Seaside-Pharo-Development.package/WARPackageBasedBrowser.class/instance/parentOfClass..st

Deal with the removal of `RPackage` and `#classTagForClass` being renamed to `#tagOf:`

Fix browser on Pharo 13

---

repository/Seaside-Pharo-Welcome.package/GRPharoPlatform.extension/instance/subclassOf.named.categorized..st
repository/Seaside-Pharo-Welcome.package/monticello.meta/categories.st
repository/Seaside-Welcome.package/GRPlatform.extension/instance/subclassOf.named.categorized..st
repository/Seaside-Welcome.package/WAWelcomeComponentCreator.class/instance/createComponent..st
repository/Seaside-Welcome.package/monticello.meta/categories.st

Factor out subclass creation and add Pharo 13 implementation.

Factor out subclass creation

---

repository/Seaside-Core.package/GRPlatform.extension/instance/seasideVersion.st
repository/Seaside-HotwireTurbo-Core.package/WAComponent.extension/instance/turboShow..st
repository/Seaside-HotwireTurbo-Examples.package/WATurboTodoItem.class/instance/renderContentOn..st
repository/Seaside-HotwireTurbo-Examples.package/WATurboTodoItem.class/instance/renderDescriptionOn..st
repository/Seaside-HotwireTurbo-Examples.package/monticello.meta/categories.st
repository/Seaside-Welcome.package/WAWelcomeGettingStarted.class/instance/renderDocumentationStepOn..st
repository/Seaside-Welcome.package/WAWelcomeGettingStarted.class/instance/renderExamplesStepOn..st
repository/Seaside-Welcome.package/monticello.meta/categories.st

- Fix Hotwire example to use show: instead of call: (makes this work on platforms that do no support full continuations)
- Improve the Welcome page a bit
- Set version to 3.5.9

Random improvements

---

repository/Seaside-Canvas.package/WATableHeadingTag.class/instance/scope..st
repository/Seaside-Core.package/WAMetaElement.class/instance/charset..st
repository/Seaside-Tests-Canvas.package/WACanvasBrushTest.class/instance/testTableData.st
repository/Seaside-Tests-Canvas.package/monticello.meta/categories.st
repository/Seaside-Tests-Functional.package/WACanvasTableFunctionalTest.class/instance/renderCurrencyTableBodyOn..st
repository/Seaside-Tests-Functional.package/WACanvasTableFunctionalTest.class/instance/renderCurrencyTableOn..st
repository/Seaside-Tests-Functional.package/WACanvasTableFunctionalTest.class/instance/renderEntityTableBodyOn..st
repository/Seaside-Tests-Functional.package/WACanvasTableFunctionalTest.class/instance/renderEntityTableColumnGroupsOn..st
repository/Seaside-Tests-Functional.package/WACanvasTableFunctionalTest.class/instance/renderEntityTableFootOn..st
repository/Seaside-Tests-Functional.package/WACanvasTableFunctionalTest.class/instance/style.st
repository/Seaside-Tests-Functional.package/WAHtml5ElementsTest.class/instance/renderContentOn..st
repository/Seaside-Tests-Functional.package/WAHtml5ElementsTest.class/instance/renderMenuOn..st
repository/Seaside-Tests-Functional.package/WALotsaLinksFunctionalTest.class/instance/renderContentOn..st
repository/Seaside-Tests-Functional.package/WAPerformanceFunctionalTest.class/instance/renderAnchorsOn..st
repository/Seaside-Tests-Functional.package/WAPerformanceFunctionalTest.class/instance/renderInline.factor.key.on..st
repository/Seaside-Tests-Functional.package/WAPhraseElementsFunctionalTest.class/instance/renderAcronymOn..st
repository/Seaside-Tests-Functional.package/WAPhraseElementsFunctionalTest.class/instance/renderContentOn..st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testCanvasTableFunctionalTest.st
repository/Seaside-Widgets.package/WASelectionDateTable.class/instance/renderCellForDate.row.index.on..st
repository/Seaside-Widgets.package/monticello.meta/categories.st

Removes the use of tags and attributes currently deprecated (or non-functioning) in HTML5 from the Seaside tests and examples.
Also fix the wrong deprecation of:
- the th.scope attribute (it was only deprecated for td tags).
- the charset attribute on meta tags
Fixes #1418

Fix html deprecations

---

repository/Seaside-Pharo-Tools-Web.package/WASeasideVersionStatus.class/instance/sortedWorkingCopies.st
repository/Seaside-Pharo-Tools-Web.package/monticello.meta/categories.st

Send #allWorkingCopies instead of  #allManagers to MCWorkingCopy if available.
`WASeasideVersionStatus` now renders with the only deprecated message being `WAMetaElement>>charset:`.

Fix MCWorkingCopy deprecations

---

.github/workflows/ci.yml
scripts/preTestingPharo.st

This pull request adds ‘GToolkit64-release’ to the list for ‘smalltalk’ in ‘ci.yml’.

Add Glamorous Toolkit

---

repository/Javascript-Tests-Core.package/JSStreamTest.class/instance/testCodecStream.st

Alternate implementation for #1442 which fixes the test and also avoids a GemStone-specific package for it.

Add test for GsDevKit/Grease issue 33

---

.github/workflows/ci.yml
repository/Seaside-Pharo-Development.package/WADevelopment.class/class/ensureAuthorInitialsWith..st
repository/Seaside-Pharo-Welcome.package/GRPharoPlatform.extension/instance/seasideIsAuthorNameSet.st
repository/Seaside-Pharo-Welcome.package/GRPharoPlatform.extension/instance/seasideSetAuthorName..st
repository/Seaside-Pharo100-Tools-Spec2.package/WAPharoControlPanel.class/class/controlPanelMenuCommandOn..st
repository/Seaside-Pharo100-Tools-Spec2.package/WAPharoControlPanel.class/class/runSeleniumServerInTerminal.st
repository/Seaside-Pharo100-Tools-Spec2.package/WAPharoControlPanel.class/class/runSeleniumServerInTerminalMenuCommandOn..st
repository/Seaside-Pharo100-Tools-Spec2.package/WAPharoControlPanel.class/class/seasideIcebergRepository.st
repository/Seaside-Pharo100-Tools-Spec2.package/WAPharoControlPanel.class/class/seasideMenuCommandOn..st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testTableReportFunctionalTest.st

- Fixes the removal of the `Author` class in Pharo 13
- Moves the Seaside control panel to it's own main menu
- Adds the selenium setup for development (on Mac only for now)

Pharo13 + other development improvements

---

repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testCallbackFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testCookieFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testDateSelectorFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testDateTimeFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testDelegationFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testEncodingFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testExceptionFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowClosureFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowClosureFunctionalTest2.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowConvenienceFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowDelegationFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowErrorFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testFlowFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testParameterFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testTaskErrorFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testUploadFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testUrlEncodingFunctionalTest.st
repository/Seaside-Tests-Parasol.package/WAWebDriverTestCase.class/instance/workaroundChromeDriver.st

Chromedriver/Selenium suddenly stopped waiting for the page to navigate after submitting in v134 of Chrome. Since it's not being fixed, I introduced a 'wait' workaround in our tests.
Discussions:
- https://issues.chromium.org/issues/402796660
- https://groups.google.com/g/selenium-users/c/vfG6A6XVkA0/m/F351RKv5BAAJw
- https://github.com/teamcapybara/capybara/issues/2800

Workaround for chomedriver/selenium issue in functional tests

---

repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/hasZinc.st
repository/Seaside-Tests-Parasol.package/WAWebDriverFunctionalTestCase.class/instance/testUploadFunctionalTestWithStreamingUploads.st
repository/Seaside-Tests-Pharo-Development.package/WAPharoDebuggerTest.class/instance/testNamedTempAt.st

- Skip Zinc streaming tests if Zinc is not loaded
- Use Squeak context API

Camp 2025 Squeak fixes round 1

---

repository/Seaside-JSON-Core.package/Object.extension/instance/jsonKeyOn..st
repository/Seaside-JSON-Core.package/WAJsonKeyValueBrush.class/class/stringKeysOnly.st
repository/Seaside-Tests-JSON.package/WAJsonRenderingTest.class/instance/testObject.st
repository/Seaside-Tests-JSON.package/WAJsonStreamTest.class/instance/testDictionaryWithNonStringKeys.st

Now an WAJsonSyntaxError is thrown when writing a JSON dictionary on the WAJsonCanvas with a key that is not a string. This is invalid JSON and was possible before.
Fixes https://github.com/SeasideSt/Seaside/issues/1474 and https://github.com/SeasideSt/Seaside/issues/1475

Writing JSON dictionaries with non-string keys is now defaulted to produce an error

---

repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselineadaptors..st

FastCGI gets pulled with Testing group.  It originally fetches and loads .mcz files into GemStone.  I have made a github repository from the previously loaded .mcz files and made changes to the baseline to match the Metacello load.

Replacing ConfigurationOf with BaselineOf; moving repository to github

---

repository/Seaside-Core.package/WARequest.class/instance/isWebSocketSetupRequest.st

The header 'connection' has the value "keep-alive, Upgrade" when firefox sends the request. This change makes the upgrade request be recognized correctly in this case.
(Chrome only sends "Upgrade" when doing the request)

Fix websocket upgrade for firefox
