SeasideSt/Seaside

.smalltalk.ston, .travis.yml
- run CI on Squeak as well
- run Pharo 6 as well
- run Squeak 5.1 as well
- run Squeak 4.6 as well
=> TravisCI updates

.smalltalk-configuration.ston
Add a CI build that's built ontop of configurations
instead of baselanes.
=> Add configuration bases CI

.smalltalk-configuration.ston, .smalltalk.ston, .travis.yml
Add a configuraiton based build.
=> Add confiugration based build

.travis.yml
=> Add Pharo 6.1 build

repository/Seaside-Pharo-Tools-Spec.package/ThemeIcons.extension/instance/seasideAdaptorRunningIcon.st, repository/Seaside-Pharo-Tools-Spec.package/ThemeIcons.extension/instance/seasideAdaptorStoppedIcon.st
=> Fix crashing adaptor icon reading in Pharo 5 and 6

repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinecommon..st
=> Reference Grease v1.4.x

tode/README.md
Simple update on readme.
A jumpstart for me to contribute on Smalltalk community.
=> Make heading looks good in tode README.md

repository/Seaside-Core.package/WAComboResponse.class/README.md, repository/Seaside-Core.package/WAComboResponse.class/properties.json
=> 1146 Fix WAComboResponse class comment

repository/Seaside-Core.package/WAFileMetadataLibrary.class/class/addFileAt.relativeToRootDirectory..st
=> 1134 Replace #replaceAll:with: with #copyReplaceAll:with:

repository/Seaside-Squeak-Tools-Web.package/WAScreenshot.class/instance/uiProcess.st
=> 1032 Fix WAScreenshot>>uiProcess problem in Squeak

repository/Seaside-Core.package/WAUrl.class/class/decodePercent..st, repository/Seaside-Core.package/WAUrl.class/class/readHexFrom.errorDetail..st, repository/Seaside-Tests-Core.package/WAUrlTest.class/instance/testDecodePercent.st, repository/Seaside-Tests-Core.package/WAUrlTest.class/instance/testInvalidSyntax.st
=> 1157 validate percent values are hex

repository/Zinc-Seaside.package/ZnZincServerAdaptor.class/instance/requestUrlFor..st
=> 1142 Avoid 'nil' scheme with Zinc

repository/Seaside-Core.package/WAAbstractFileLibrary.class/class/defaultMimeTypes.st
=> Add .less support to WAFileLibrary

repository/Javascript-Core.package/JSObject.class/instance/timeout..st, repository/Seaside-Core.package/WAHtmlRoot.class/instance/beXhtml10Strict.st, repository/Seaside-Core.package/WAHtmlRoot.class/instance/beXhtml10Transitional.st, repository/Seaside-Core.package/WAHtmlRoot.class/instance/beXhtml11.st
what the title says, see https://github.com/SeasideSt/Seaside/wiki/Seaside330Changelog#deprecated-features
=> Remove the methods that were deprecated in v3.3.0

repository/Seaside-Core.package/WAMimeType.class/instance/isBinary.st, repository/Seaside-Tests-Core.package/WAMimeTypeTest.class/instance/testIsBinary.st
=> XML subtypes should be text

repository/Seaside-Component.package/WAComponent.class/instance/decoration..st, repository/Seaside-Component.package/WAComponent.class/instance/decoration.st, repository/Seaside-Component.package/WAComponent.class/instance/initialize.st
=> Revert lazy initialization of WAComponent>>decoration 

repository/Seaside-Pharo-Development.package/WAPharoWalkback.class/instance/tempNamesAndValuesIn.do..st
=> Fix WAPharoCallback for use in Squeak

.github/workflows/ci.yml, .github/workflows/main.yml, repository/.gitattributes, repository/Seaside-Tests-Functional.package/WADateSelectorFunctionalTest.class/instance/renderDateSelectorsOn..st
As Travis-CI is seriously [limiting build time for open-source projects]( https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) and smalltalkCI has a working github action, I considered giving github actions a try for the Seaside builds. 
And it's going pretty well.
=> Setup builds via github actions

repository/Seaside-Core.package/WAUrl.class/instance/withoutSeasideQueryFields.st, repository/Seaside-Tests-Core.package/WAUrlTest.class/instance/testWithoutSeasideQueryFields.st
Adds #withoutSeasideQueryFields to WAUrl
=> WAURL>>#urlWithoutSeasideFields

README.md
Add VAST installation instructions
=> Add VAST installation instructions

repository/Seaside-Core.package/WAUrl.class/class/readHexFrom.errorDetail..st
=> Fixes issue #1283

repository/Seaside-Core.package/WAComboResponse.class/README.md
=> When streaming the #response is flushed

repository/Seaside-Core.package/WAUrl.class/instance/postCopy.st
=> Check for nil in WAUrl >> #postCopy

repository/Seaside-Core.package/WAAbstractFileLibrary.class/class/compileText.selector..st
=> Switch to #asMethodReturningString:named:

repository/JQuery-Tests-UI.package/JQEffectFunctionalTest.class/instance/renderContentOn..st, repository/Seaside-Canvas.package/WACollectionTag.class/instance/on.of..st, repository/Seaside-Canvas.package/WACompound.class/instance/on.of..st, repository/Seaside-Canvas.package/WAFileUploadTag.class/instance/on.of..st, repository/Seaside-Canvas.package/WAFormInputTag.class/instance/on.of..st
=> Replace senders of asMutator with greaseAsMutator

README.md
Replace http address with the https one.
=> README: fix Pharo URL

repository/Seaside-Pharo-Tools-Web.package/WASpaceStatus.class/instance/spaceTallyItems.st
Fixes the Space tab (is still slow, but it loads)
=> Fixes sending sort message to the wrong object to display the tally.
